// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportHTML(arg1, arg2) {
  return window['go']['main']['App']['ExportHTML'](arg1, arg2);
}

export function GetFileStats(arg1) {
  return window['go']['main']['App']['GetFileStats'](arg1);
}

export function GetInitialFile() {
  return window['go']['main']['App']['GetInitialFile']();
}

export function GetPendingFile() {
  return window['go']['main']['App']['GetPendingFile']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ReadFileAtPath(arg1) {
  return window['go']['main']['App']['ReadFileAtPath'](arg1);
}

export function RenderMarkdown(arg1) {
  return window['go']['main']['App']['RenderMarkdown'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileAs(arg1) {
  return window['go']['main']['App']['SaveFileAs'](arg1);
}
