// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportHTML(arg1:string,arg2:string):Promise<string>;

export function GetFileStats(arg1:string):Promise<main.FileStats>;

export function GetInitialFile():Promise<main.FilePayload>;

export function OpenFile():Promise<main.FilePayload>;

export function ReadFileAtPath(arg1:string):Promise<main.FilePayload>;

export function RenderMarkdown(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveFileAs(arg1:string):Promise<string>;
